### ISSUE TITLE
how to use with rkdeveloptool?

### ISSUE THREAD

**Issue by DaveWK** [7Ji/orangepi5-rkloader#2]
Hi,

I have an orange pi 5b and would like to flash the mainline rkloader to the emmc using rkdeveloptool. I was not sure what extent I should be using, as it appears when uncompressed the mainline image is 17 megs vs the vendor image which is 4 mb.

flashing via rkdeveloptool after using the MASKROM button on the board seems to be the most reliable way to flash a single image. I would appreciate the instructions assume that I am using rkdeveloptool in MASKROM mode, then to be able to flash the "rkloader included" full image from the archlinuxarm repo, and then have instructions in this repo that has the cli syntax to overwrite the rkloader partition with the correct `rkdeveloptool wl <address>`  command.  

Alternatively, if I could get the `dd` command along with the extents to overwrite the rkloader from the archlinuxarm image, then just use `rkdeveloptool wl 0x0` on a single image, that would be great too

**Comment by 7Ji** [comment]
I never used rkdevtool. 

Just dd the whole image to sd/emmc/spi, with conv=notrunc. If it complains target size not enough for spi you don't need to care about that. The actual data is only 9.1MiB, and I've created a partition in the table taking first 16MiB to hint on unsafe area (It's 17MiB because GPT needs a little extra in the end).  The partition table is only useful when you flash it to SD/eMMC to help you identify unsafe areas to create partitions on.

**Comment by 7Ji** [comment]
Cloesd by https://github.com/7Ji/orangepi5-rkloader/commit/fc63dfdeed2cb65dc487ffd47cdde4c4e51a0a5c
